description: VTAW testing
directory:
  target: Data
# optional game metadata
game:
  # optional, but best practice to include the game executable name
  executable: SkyrimSE.exe
  # gameVersion optional, defaults to all versions. Used to enforce game version compatibility between mods
  version: "<=v1.5.97"
# name is optional will default to the repo name
name: VTAW
# mod ESRB rating. if none specified then mod is safe for all ages.
rating:
  esrb: M # one of E, eC, E10+, T, M, AO
# url optional for mod releases. defaults to releases archive
url: "https://github.com/afloesch/sse-vtaw/releases/download/v1.0.0/Vtaw.Wardrobe.5.-.CBBE.SE.-.CBBE.SMP.-.BodySlide-44838-1-0-1612017028.7z"
# version/tag required
version: v1.0.0